### ISSUE TITLE
Create Student Relation

### ISSUE THREAD

**Issue by HironKanishka97** [MyPlaygroundDEP/sql-joins-example-team#2]
![image](https://github.com/user-attachments/assets/2e5c237d-ebcf-4796-9dd1-dc3b77760a6d)

**Comment by rawcode69** [comment]
Image is not attached. Attached karapan

**Comment by rawcode69** [comment]
This issue was moved to review. Please give your confirmation for further develop

**Comment by HironKanishka97** [comment]
ok permission granted
