### ISSUE TITLE
Create Exam Relation

### ISSUE THREAD

**Issue by HironKanishka97** [MyPlaygroundDEP/sql-joins-example-team#8]
![Image](https://github.com/user-attachments/assets/17bea7ad-cf6f-4d87-b5d2-86974c8de5cf)

**Comment by UDEEKA** [comment]
@Prajeeth-W @HironKanishka97  @rawcode69 I want to add module_id as a foreign key for exam table? how do I do it?

**Comment by HironKanishka97** [comment]
@Prajeeth-W  please respond

**Comment by UDEEKA** [comment]
@HironKanishka97 Please review this
